// Het Engels van Sticky Clash. Links de Nederlandse tekst precies zoals hij in de code of
// in index.html staat, rechts het Engels. Zie js/taal.js voor hoe het werkt.
//
// Zelf iets veranderen: pas alleen de rechterkant aan. Laat {naam}, {n} en dergelijke
// staan: daar vult het spel zelf iets in (een getal, een naam). Verander je een zin links
// in de code, verander hem dan hier ook, anders blijft hij in het Engels Nederlands.
// test/taal.mjs controleert of alles erin staat.

export const TAAL_EN = {
  // ---- het paneel (index.html)
  'Sticky Clash — projection mapping game': 'Sticky Clash — projection mapping game',
  'Klik op "Alles automatisch instellen"': 'Click "Set up everything automatically"',
  'Taal': 'Language',
  'Alles automatisch instellen': 'Set up everything automatically',
  'Camera': 'Camera',
  'Automatisch — losse webcam als die er is': 'Automatic — external webcam if there is one',
  'Geen webcam? Je telefoon kan het ook, met een gratis app als DroidCam of Camo. Op een Mac kan een iPhone meteen als camera.':
    'No webcam? Your phone can do it too, with a free app like DroidCam or Camo. On a Mac, an iPhone works as a camera right away.',
  'Beamer': 'Projector',
  'Kalibratie': 'Calibration',
  'Muur geleerd': 'Wall learned',
  'Doel gevonden': 'Goal found',
  'Doet de beamer, de camera, de kalibratie en de muur in één keer. Volg de aanwijzingen op de muur.':
    'Sets up the projector, camera, calibration and wall in one go. Follow the instructions on the wall.',
  'Afbreken': 'Cancel',
  'Installeer als app': 'Install as app',
  'Eigen venster en pictogram, en daarna start het spel ook zonder internet.': 'Its own window and icon, and after that the game also starts without internet.',
  'Speelmodus': 'Play mode',
  'Elk voorwerp': 'Any object',
  'Post-its · duel': 'Post-its · duel',
  'Gevoeligheid': 'Sensitivity',
  'Hoger = pakt ook zwakkere verschillen op. Te hoog en de hele muur licht op.': 'Higher = picks up fainter differences too. Too high and the whole wall lights up.',
  'Muurverlichting': 'Wall light',
  'Automatisch afstellen bij instellen': 'Adjust automatically during setup',
  'De beamer verlicht de muur zachtjes, zodat de camera je voorwerpen ook in een donkere kamer ziet.':
    'The projector gently lights the wall, so the camera can see your objects even in a dark room.',
  'Mensen negeren': 'Ignore people',
  'Huid negeren — je arm verdwijnt, het voorwerp in je hand blijft': 'Ignore skin — your arm disappears, the object in your hand stays',
  'Wat al aan de muur hangt telt ook mee': 'Things already on the wall count too',
  'Leer opnieuw hoe de lege muur eruitziet': 'Relearn what the empty wall looks like',
  'Muur opnieuw leren': 'Relearn wall',
  'Doel aanwijzen': 'Mark goal',
  'Foto van wat de camera ziet': 'Photo of what the camera sees',
  'Wordt iets niet goed herkend? Klik hierop en stuur de foto op: dan is precies te zien wat er gebeurt.':
    "Something not recognized properly? Click this and send the photo along: it shows exactly what's going on.",
  'Start ronde': 'Start round',
  'Reset': 'Reset',
  'Testmodus (muis, geen camera)': 'Test mode (mouse, no camera)',
  'Telefoon': 'Phone',
  'Telefoon koppelen': 'Connect phone',
  'Scan de code met je telefoon. Zolang er niet gespeeld wordt staat hij ook op de muur. Geen scanner? Open op je telefoon:':
    "Scan the code with your phone. While no round is being played, it's on the wall too. No scanner? On your phone, open:",
  'Code ook op de muur': 'Show the code on the wall too',
  'Nieuwe code': 'New code',
  'Stoppen': 'Stop',
  'Starten, pauzeren en je naam voor de ranglijst typen vanaf je telefoon. Laptop én telefoon hebben internet nodig: de knoppen gaan via ntfy.sh, en daar wordt niets bewaard.':
    'Start, pause and type your name for the leaderboard from your phone. The laptop and the phone both need internet: the buttons go through ntfy.sh, and nothing is stored there.',
  'Ranglijst': 'Leaderboard',
  'Nieuwe score! Hoe heet je?': "New score! What's your name?",
  'Naam': 'Name',
  'Opslaan': 'Save',
  'Ranglijst wissen': 'Clear leaderboard',
  'Spelregels': 'Game rules',
  'Spelvorm': 'Game type',
  'Vrij spel — zo veel mogelijk in de tijd': 'Free play — score as many as you can in time',
  'Uitdaging — steeds moeilijkere levels': 'Challenge — levels that keep getting harder',
  'Speciale briefjes: rood = trampoline, groen = turbo, blauw = breekt na 5 tikken': 'Special notes: red = trampoline, green = turbo, blue = breaks after 5 hits',
  'Gouden ballen — 3 punten': 'Gold balls — 3 points',
  'Bonusbak — 3 punten, verspringt elke 20 seconden': 'Bonus bin — 3 points, moves every 20 seconds',
  'Rondetijd': 'Round time',
  'Geen tijdslimiet — blijft doorgaan': 'No time limit — keeps going',
  'Balbron beweegt heen en weer': 'Ball source moves back and forth',
  'tempo': 'speed',
  'Bak beweegt heen en weer': 'Bin moves back and forth',
  'Wind': 'Wind',
  'uit': 'off',
  'Wind duwt de ballen langzaam heen en weer. Je ziet de richting boven in beeld.': 'Wind slowly pushes the balls back and forth. The direction is shown at the top of the screen.',
  'Meer instellingen': 'More settings',
  'Camera starten': 'Start camera',
  'Spiegelen': 'Mirror',
  'Belichting vastzetten — alleen als het beeld flikkert': 'Lock exposure — only if the image flickers',
  "Op sommige camera's wordt het beeld dan donkerder. Het spel controleert dat en zet hem dan terug.":
    'On some cameras this makes the image darker. The game checks for that and switches it back.',
  'Venster openen': 'Open window',
  'Sluiten': 'Close',
  'Beamerscherm herkennen': 'Detect projector screen',
  'Eén keer toestaan, daarna opent het beamervenster voortaan vanzelf op de beamer.': 'Allow it once, and from then on the projector window opens on the projector by itself.',
  'Staat het niet vanzelf op volledig scherm, klik dan één keer in dat venster. Het spel kalibreert zich daarna vanzelf opnieuw.':
    'Not full screen by itself? Click once in that window. The game then recalibrates by itself.',
  'Automatisch': 'Automatic',
  'Met de hand': 'Manual',
  'Wissen': 'Clear',
  'Niet gekalibreerd': 'Not calibrated',
  'Vanzelf opnieuw instellen als de camera of beamer verschuift': 'Redo setup automatically if the camera or projector moves',
  'Kleuren': 'Colors',
  '(duelmodus)': '(duel mode)',
  'Klik "Leren" en klik daarna op het voorwerp in het camerabeeld.': 'Click "Learn", then click the object in the camera view.',
  'Spel': 'Game',
  'Min. grootte': 'Min. size',
  'Max. grootte': 'Max. size',
  'Stilstaan': 'Hold still',
  'Mensenfilter': 'People filter',
  'Hoger = strenger. Het filter kijkt of een vorm star is: een voorwerp houdt zijn omtrek, een mens niet.':
    "Higher = stricter. The filter checks whether a shape is rigid: an object keeps its outline, a person doesn't.",
  'Zwaartekracht': 'Gravity',
  'Stuiter': 'Bounce',
  'Baltempo': 'Ball rate',
  'Geluid': 'Sound',
  'Muziek — zacht, alleen tijdens een ronde': 'Music — soft, only during a round',
  'Effecten — confetti, sterretjes, COMBO en feest bij een record': 'Effects — confetti, sparkles, COMBO and a celebration for a record',
  'Voorwerpen omlijnen op de muur': 'Outline objects on the wall',
  'Uit in voorwerpmodus: licht op een voorwerp maakt dat voorwerp onzichtbaar voor de camera. Op je laptop zie je de omlijningen altijd.':
    'Off in object mode: light on an object makes it invisible to the camera. You always see the outlines on your laptop.',
  // de uitleg onderaan, in stukjes rond de toetsen
  'Doel en bron verplaatsen:': 'Moving the goal and source:',
  'sleep ze met de muis in de rechter weergave. Het doel pak je door erin te klikken, de bron met':
    'drag them with the mouse in the right-hand view. Grab the goal by clicking inside it, the source with',
  '+klik. Of met de pijltjestoetsen en': '+click. Or use the arrow keys and',
  'spatie': 'space',
  '= pauze.': '= pause.',
  'Beeld': 'Image',
  'Wat het spel ziet': 'What the game sees',
  'Wat de beamer laat zien': 'What the projector shows',
  'Kon het spel niet laden — open sticky-clash.html, of start via start.bat': "Couldn't load the game — open sticky-clash.html, or start it with start.bat",

  // ---- knoppen en meldingen (main.js)
  'Er ging iets mis: {fout}': 'Something went wrong: {fout}',
  'Camera {n}': 'Camera {n}',
  '{naam} (ingebouwd)': '{naam} (built-in)',
  'Camera mislukt: de camera mag niet — klik in de adresbalk op het camera-icoon en kies Toestaan':
    "Camera failed: the camera isn't allowed — click the camera icon in the address bar and choose Allow",
  'Camera mislukt: de camera is bezet — sluit Teams, Zoom, OBS of de Camera-app en probeer opnieuw':
    'Camera failed: the camera is in use — close Teams, Zoom, OBS or the Camera app and try again',
  'Camera mislukt: geen camera gevonden — sluit je webcam aan': 'Camera failed: no camera found — connect your webcam',
  'Camera mislukt: {fout}': 'Camera failed: {fout}',
  'Camera mislukt: onbekende fout': 'Camera failed: unknown error',
  'De gekozen camera deed het niet (bezet?) — nu: {naam}': "The selected camera didn't work (in use?) — now using: {naam}",
  'Andere camera dan bij de kalibratie — klik "Alles automatisch instellen"': 'Different camera than during calibration — click "Set up everything automatically"',
  'De camera is weggevallen — controleer de kabel en klik "Camera starten"': 'The camera dropped out — check the cable and click "Start camera"',
  'De camera staat nog op vaste belichting — trek de camera er even uit en weer in': 'The camera is still on fixed exposure — unplug the camera and plug it back in',
  'Camera actief: {naam}': 'Camera active: {naam}',
  'nieuwe camera': 'new camera',
  'Webcam gevonden: {naam} — kies hem bovenaan bij Camera': 'Webcam found: {naam} — pick it at the top under Camera',
  'Webcam gevonden en gekozen: {naam} — klik op "Alles automatisch instellen"': 'Webcam found and selected: {naam} — click "Set up everything automatically"',
  'Webcam gevonden en gekozen: {naam} — klik op "Alles automatisch instellen" om hem af te stellen':
    'Webcam found and selected: {naam} — click "Set up everything automatically" to set it up',
  'De webcam is losgekoppeld — steek hem er weer in, of kies bovenaan een andere camera': 'The webcam was unplugged — plug it back in, or pick another camera at the top',
  'Camera gekozen — klik op "Alles automatisch instellen"': 'Camera selected — click "Set up everything automatically"',
  'Camera: automatisch': 'Camera: automatic',
  'Pop-up geblokkeerd — sta pop-ups toe voor deze pagina en probeer opnieuw': 'Pop-up blocked — allow pop-ups for this page and try again',
  'Sticky Clash — beamer': 'Sticky Clash — projector',
  'Klik één keer in het beamervenster voor volledig scherm': 'Click once in the projector window for full screen',
  'Deze browser kan geen schermen herkennen — sleep het beamervenster zelf naar de beamer': "This browser can't detect screens — drag the projector window to the projector yourself",
  'Geen toestemming gekregen — sleep het beamervenster zelf naar de beamer': 'No permission given — drag the projector window to the projector yourself',
  'Maar één scherm gevonden — sluit de beamer aan en probeer opnieuw': 'Only one screen found — connect the projector and try again',
  'Beamer gevonden ({b}×{h}) — het beamervenster opent daar voortaan vanzelf': 'Projector found ({b}×{h}) — the projector window will open there by itself from now on',
  'Start eerst de camera': 'Start the camera first',
  'Open eerst het beamervenster': 'Open the projector window first',
  'De camera ziet het beamerbeeld niet (contrast {n}). Staat het beamervenster op de beamer, en kijkt de camera naar dat vlak?':
    "The camera can't see the projected image (contrast {n}). Is the projector window on the projector, and is the camera pointed at it?",
  'Het beamervlak is te klein in beeld. Richt de camera op de muur.': 'The projected area is too small in the camera view. Point the camera at the wall.',
  'Het beamervlak ligt niet volledig in beeld.': "The projected area isn't fully in the camera view.",
  'Kalibratie mislukt.': 'Calibration failed.',
  'Kalibratie gelukt — controleer of de gestreepte lijn om het beamerbeeld ligt': 'Calibration done — check that the dashed line runs around the projected image',
  'Kalibratie gelukt (grove meting; stippen waren niet goed zichtbaar)': "Calibration done (rough measurement; the dots weren't clearly visible)",
  'Klik punt {n} van 4 in het camerabeeld': 'Click point {n} of 4 in the camera view',
  'Gekalibreerd': 'Calibrated',
  'Vastzetten maakte het camerabeeld donkerder — belichting blijft automatisch': 'Locking made the camera image darker — exposure stays automatic',
  'Muur geleerd — alles wat je er nu voor zet, kaatst de ballen': 'Wall learned — anything you put in front of it now bounces the balls',
  'Muur geleerd — {n} voorwerp hing er al, dat telt gewoon mee': 'Wall learned — {n} object was already there, and it counts too',
  'Muur geleerd — {n} voorwerpen hingen er al, die tellen gewoon mee': 'Wall learned — {n} objects were already there, and they count too',
  'Muur geleerd en camera vastgezet ({wat}) — alles wat je er nu voor zet, kaatst de ballen':
    'Wall learned and camera locked ({wat}) — anything you put in front of it now bounces the balls',
  'Muur geleerd en camera vastgezet ({wat}) — {n} voorwerp hing er al, dat telt gewoon mee':
    'Wall learned and camera locked ({wat}) — {n} object was already there, and it counts too',
  'Muur geleerd en camera vastgezet ({wat}) — {n} voorwerpen hingen er al, die tellen gewoon mee':
    'Wall learned and camera locked ({wat}) — {n} objects were already there, and they count too',
  'belichting': 'exposure',
  'witbalans': 'white balance',
  'Geen bak gevonden — probeer "Doel aanwijzen" en klik erop in het camerabeeld': 'No bin found — try "Mark goal" and click it in the camera view',
  'Doel gevonden — verplaats de bak gerust tijdens het spel': 'Goal found — feel free to move the bin during the game',
  'Klik op de bak in het camerabeeld links': 'Click the bin in the camera view on the left',
  'Alles staat klaar — klik op "Start ronde"': 'All set — click "Start round"',
  'Klaar, maar geen bak gevonden — sleep het doel in de rechter weergave naar je bak': 'Done, but no bin found — drag the goal onto your bin in the right-hand view',
  'Opnieuw instellen': 'Set up again',
  'Afgebroken': 'Cancelled',
  'Alles wat je voor de muur houdt kaatst de ballen — boek, doos, hand, wat je maar pakt. Leer eerst de lege muur.':
    'Anything you hold in front of the wall bounces the balls — a book, a box, your hand, whatever you grab. Learn the empty wall first.',
  'Oranje post-its sturen de ballen naar de bak, blauwe blokkeren. Leer de twee kleuren onder "Meer instellingen".':
    'Orange post-its steer the balls to the bin, blue ones block them. Teach it the two colors under "More settings".',
  'Klik…': 'Click…',
  'Leren': 'Learn',
  'Aanvaller': 'Attacker',
  'Verdediger': 'Defender',
  'Doel': 'Goal',
  'Balbron': 'Ball source',
  'Eerst kalibreren': 'Calibrate first',
  'Doel gezet': 'Goal set',
  '{kleur} geleerd: tint {tint}°': '{kleur} learned: hue {tint}°',
  'Kalibratie gelukt': 'Calibration done',
  'Kalibratie mislukt — klik de punten in de juiste volgorde': 'Calibration failed — click the points in the right order',
  'Muurverlichting veranderd — klik "Muur opnieuw leren" voor de beste herkenning': 'Wall light changed — click "Relearn wall" for the best detection',
  'Belichting wordt vastgezet bij het leren van de muur': 'Exposure will be locked when the wall is learned',
  'Belichting weer automatisch': 'Exposure back to automatic',
  'Wat er al hing telt niet meer mee': 'Things already on the wall no longer count',
  '{n} voorwerp hing er al, dat telt nu mee': '{n} object was already there, and it counts now',
  '{n} voorwerpen hingen er al, die tellen nu mee': '{n} objects were already there, and they count now',
  'Er hing niets op de muur toen hij geleerd werd': 'Nothing was on the wall when it was learned',
  'Testmodus: sleep met de muis in de rechter weergave': 'Test mode: drag with the mouse in the right-hand view',
  'Testmodus uit': 'Test mode off',
  'Nog geen scores — speel een ronde': 'No scores yet — play a round',
  'level {n}': 'level {n}',
  '{n} punt': '{n} point',
  '{n} punten': '{n} points',
  'Level {n} — dat haalt de ranglijst! Hoe heet je?': "Level {n} — that makes the leaderboard! What's your name?",
  '{n} punt — dat haalt de ranglijst! Hoe heet je?': "{n} point — that makes the leaderboard! What's your name?",
  '{n} punten — dat haalt de ranglijst! Hoe heet je?': "{n} points — that makes the leaderboard! What's your name?",
  'Anoniem': 'Anonymous',
  'Opgeslagen in de ranglijst: {naam}': 'Saved to the leaderboard: {naam}',
  'De ranglijst van deze spelvorm wissen?': 'Clear the leaderboard for this game type?',
  'De camera of beamer is verschoven — klik op "Alles automatisch instellen"': 'The camera or projector has moved — click "Set up everything automatically"',
  'De camera of beamer is verschoven — ik stel alles opnieuw in': 'The camera or projector has moved — setting everything up again',
  'Opnieuw instellen lukte niet — klik op "Alles automatisch instellen"': 'Setting up again didn\'t work — click "Set up everything automatically"',
  'Opnieuw ingesteld': 'Everything set up again',
  'Opnieuw ingesteld — klik op "Pauze opheffen" om verder te spelen': 'Everything set up again — click "Resume" to keep playing',
  'Pauze': 'Pause',
  'Pauze opheffen': 'Resume',
  'Beeld bijgesneden tot het beamervlak — {zoom}× meer detail': 'Image cropped to the projected area — {zoom}× more detail',
  'Het is erg donker — de camera ziet weinig, ook met de muurverlichting. Doe een lamp aan':
    "It's very dark — the camera sees little, even with the wall light. Switch on a lamp",
  'Het camerabeeld staat stil — sluit programma\'s die de camera gebruiken, of kies een andere camera':
    'The camera image is frozen — close programs that use the camera, or pick another camera',
  'Camerabeeld is terug': 'Camera image is back',
  'Uitdaging voorbij: je haalde level {n}': 'Challenge over: you reached level {n}',
  'Nieuw record: {n} doelpunt': 'New record: {n} goal',
  'Nieuw record: {n} doelpunten': 'New record: {n} goals',
  'Ronde afgelopen': 'Round over',
  'Losse versie: de browser vraagt bij elke start om de camera — klik dan op Toestaan. Wil je dat hij het onthoudt, start dan via start.bat.':
    'Single-file version: the browser asks for the camera every time you start — just click Allow. Want it to remember? Start with start.bat instead.',
  'Open sticky-clash.html of start.bat — zo geeft de browser geen camera vrij': "Open sticky-clash.html or start.bat — opened like this, the browser won't allow the camera",
  'Werkt het best in Chrome of Edge — in deze browser kan het beamervenster haperen': 'Works best in Chrome or Edge — in this browser the projector window may stutter',
  'De camera wisselde van beeldformaat — leer de muur opnieuw': 'The camera changed its image format — relearn the wall',

  // ---- de teller onder "Doel aanwijzen"
  '{n} obstakel (testmodus)': '{n} obstacle (test mode)',
  '{n} obstakels (testmodus)': '{n} obstacles (test mode)',
  'Niet gekalibreerd — voorwerpen raken de ballen niet': "Not calibrated — objects don't touch the balls",
  'Muur nog niet geleerd': 'Wall not learned yet',
  'Bijna alles wordt als voorwerp gezien — licht veranderd? Leer de muur opnieuw': 'Almost everything is seen as an object — did the light change? Relearn the wall',
  'Het licht is flink veranderd — herkenning werkt beperkt. Leer de muur opnieuw': 'The light has changed a lot — detection is limited. Relearn the wall',
  'De camera ziet te weinig licht ({n}/255) — zet Muurverlichting hoger of doe een lamp aan': 'The camera sees too little light ({n}/255) — turn Wall light up or switch on a lamp',
  '{n} voorwerp actief': '{n} object active',
  '{n} voorwerpen actief': '{n} objects active',
  'genegeerd: {lijst}': 'ignored: {lijst}',
  'loopt beeld uit': 'leaves the frame',
  'te groot': 'too big',
  'buiten beamervlak': 'outside projection',
  'te hoog': 'too high',
  'mens': 'person',
  'geen voorwerpvorm': 'not an object shape',
  'donker of schaduw (telt als het stil hangt)': 'dark or shadow (counts once it hangs still)',
  'huidkleur (telt als het stil hangt)': 'skin color (counts once it hangs still)',
  'schaduw van de bak': 'shadow of the bin',
  '{n} vlek te klein — zet Min. grootte lager, of Gevoeligheid hoger': '{n} blob too small — lower Min. size, or raise Sensitivity',
  '{n} vlekken te klein — zet Min. grootte lager, of Gevoeligheid hoger': '{n} blobs too small — lower Min. size, or raise Sensitivity',

  // ---- de diagnosefoto (knop "Foto van wat de camera ziet")
  'Camera, met wat het spel herkent': 'Camera, with what the game recognizes',
  'Wat het spel als voorwerp ziet (licht = voorgrond)': 'What the game sees as objects (light = foreground)',
  'ja': 'yes',
  'nee': 'no',
  'aan': 'on',
  'Camera: {naam}  {b}x{h}': 'Camera: {naam}  {b}x{h}',
  '(uitsnede)': '(cropped)',
  'uitdaging': 'challenge',
  'Kalibratie: {kal}   Muur geleerd: {muur}   Modus: {modus}': 'Calibration: {kal}   Wall learned: {muur}   Mode: {modus}',
  'Gevoeligheid {sens}   Muurverlichting {licht}%   Huid negeren {huid}   Mensen negeren {mensen}':
    'Sensitivity {sens}   Wall light {licht}%   Ignore skin {huid}   Ignore people {mensen}',
  'Camera ziet helderheid {l}/255   voorgrond {fg}%   lichtcorrectie {gain}   {fps}': 'Camera sees brightness {l}/255   foreground {fg}%   light correction {gain}   {fps}',
  'Teller: {teller}': 'Counter: {teller}',
  'Sporen (id · cellen · oordeel · huid · schaduw · vertrouwd · stil · trilling · soort):': 'Tracks (id · cells · verdict · skin · shadow · trusted · still · jitter · kind):',
  // oordeel per spoor en soort briefje (korte codes uit main.js en vision.js)
  'wacht': 'waiting',
  'telt': 'counts',
  'bak': 'bin',
  'rand': 'edge',
  'groot': 'big',
  'buiten': 'outside',
  'vorm': 'shape',
  'schaduw': 'shadow',
  'huid': 'skin',
  'trampoline': 'trampoline',
  'booster': 'booster',
  'breek': 'breakable',
  '… en nog {n}': '… and {n} more',
  'sticky-clash-foto': 'sticky-clash-photo',
  'Foto opgeslagen in je map Downloads ({bestand})': 'Photo saved in your Downloads folder ({bestand})',

  // ---- op de muur tijdens het instellen (main.js). De titels staan heel groot op de muur:
  // houd ze kort, anders passen ze niet op een beamer van 4:3.
  'Kalibreren': 'Calibrating',
  'even niet voor de beamer gaan staan': "please don't stand in front of the projector",
  'Ga even uit beeld': 'Step out of view',
  'ik leer hoe de lege muur eruitziet': "I'm learning what the empty wall looks like",
  'Momentje': 'One moment',
  'Zet nu de bak neer': 'Now place the bin',
  'en ga daarna zelf uit beeld': 'then step out of view yourself',
  'Zoeken…': 'Searching…',
  'Licht afstellen': 'Adjusting the light',
  'Klaar': 'All set',
  'veel plezier': 'have fun',
  'Klik kruis {n} aan in het camerabeeld op de laptop': 'Click cross {n} in the camera view on the laptop',
  'Klik één keer in dit venster voor volledig scherm': 'Click once in this window for full screen',
  'NIET GEKALIBREERD': 'NOT CALIBRATED',
  'voorwerpen raken de ballen niet — klik op "Alles automatisch instellen"': 'objects don\'t touch the balls — click "Set up everything automatically"',
  'Camera nog niet gestart': 'Camera not started yet',

  // ---- tips op de muur zolang er niet gespeeld wordt (main.js)
  'Plak briefjes of houd voorwerpen tegen de muur: de ballen kaatsen ertegen': 'Stick notes or hold objects against the wall: the balls bounce off them',
  'Bouw een baan naar de groene bak': 'Build a path to the green bin',
  'Rood briefje = trampoline · groen = turbo · blauw = breekt na 5 tikken': 'Red note = trampoline · green = turbo · blue = breaks after 5 hits',
  'Een gouden bal in de bak is 3 punten waard': 'A gold ball in the bin is worth 3 points',
  'De kleine gouden bak geeft 3 punten, en verspringt steeds': 'The small gold bin gives 3 points, and keeps moving',
  'Uitdaging: haal elk level op tijd — het wordt steeds moeilijker': 'Challenge: clear each level in time — it keeps getting harder',
  'Druk op spatie om te beginnen': 'Press space to start',

  // ---- het spel op de muur (game.js)
  'AANVALLER': 'ATTACKER',
  'VERDEDIGER': 'DEFENDER',
  'DOELPUNTEN': 'GOALS',
  'GEMIST': 'MISSED',
  'LEVEL {n}': 'LEVEL {n}',
  'COMBO x{n}': 'COMBO x{n}',
  'COMBO ×{n}': 'COMBO ×{n}',
  'GO': 'GO',
  'KRAK': 'CRACK',
  'BLOK': 'BLOCK',
  'BOING': 'BOING',
  'TURBO': 'TURBO',
  'zet je voorwerpen klaar': 'get your objects ready',
  'LEVEL 1: {n} punten in {s} s': 'LEVEL 1: {n} points in {s} s',
  'LEVEL {level}: de bron beweegt en er komen meer ballen — {n} punten in {s} s': 'LEVEL {level}: the source moves and more balls fall — {n} points in {s} s',
  'LEVEL {level}: er staat wind — {n} punten in {s} s': 'LEVEL {level}: wind is blowing — {n} points in {s} s',
  'LEVEL {level}: meer punten — {n} punten in {s} s': 'LEVEL {level}: more points — {n} points in {s} s',
  'LEVEL {level}: de bak beweegt — {n} punten in {s} s': 'LEVEL {level}: the bin moves — {n} points in {s} s',
  'LEVEL {level}: de bak verhuist — {n} punten in {s} s': 'LEVEL {level}: the bin moves to a new spot — {n} points in {s} s',
  'LEVEL {n} GEHAALD': 'LEVEL {n} CLEARED',
  'LEVEL {n} — GAME OVER': 'LEVEL {n} — GAME OVER',
  'PAUZE': 'PAUSED',
  'KLAAR OM TE STARTEN': 'READY TO START',
  'hoogste score tot nu toe: {n}': 'high score so far: {n}',
  'zet iets voor de muur en start de ronde': 'put something in front of the wall and start the round',
  'druk op spatie voor een nieuwe ronde': 'press space for a new round',
  'druk op spatie voor een nieuwe poging': 'press space to try again',
  '{n} DOELPUNT': '{n} GOAL',
  '{n} DOELPUNTEN': '{n} GOALS',
  'GELIJKSPEL': 'DRAW',
  'AANVALLER WINT': 'ATTACKER WINS',
  'VERDEDIGER WINT': 'DEFENDER WINS',
  'NIEUW RECORD': 'NEW RECORD',
  'RANGLIJST': 'LEADERBOARD',

  // ---- bediening met de telefoon (telefoon.js). De meldingen gaan naar de telefoon en
  // staan daarom ook in telefoon.html, met dezelfde vertaling.
  'Telefoon verbonden': 'Phone connected',
  '{n} telefoons verbonden': '{n} phones connected',
  'Klaar — wacht op je telefoon': 'Ready — waiting for your phone',
  'Verbinden met ntfy.sh…': 'Connecting to ntfy.sh…',
  'Verbinding met ntfy.sh weg — opnieuw verbinden…': 'Connection to ntfy.sh lost — reconnecting…',
  'Geen verbinding met ntfy.sh — opnieuw over {n} s. Heeft de laptop internet?': 'No connection to ntfy.sh — retrying in {n} s. Does the laptop have internet?',
  'ntfy.sh vraagt om rustiger aan te doen — volgende poging over {n} s': 'ntfy.sh asks us to slow down — next try in {n} s',
  'Bericht naar de telefoon mislukt — opnieuw over {n} s': 'Message to the phone failed — retrying in {n} s',
  'Even wachten: het spel is nog aan het instellen': 'One moment: the game is still setting up',
  'Even wachten: het spel stelt zich opnieuw in': 'One moment: the game is setting itself up again',
  'De ronde begint al': 'The round is already starting',
  'Er loopt al een ronde': 'A round is already running',
  'Staat al op pauze': 'Already paused',
  'Er loopt geen ronde': 'No round is running',
  'Het spel loopt al': 'The game is already running',
  'Er is geen pauze': "The game isn't paused",
  'Zet de ronde eerst op pauze': 'Pause the round first',
  'Er wordt nu geen naam gevraagd': "No name is being asked for right now",
  'Opgeslagen in de ranglijst': 'Saved to the leaderboard',
};
